### ISSUE TITLE
i need to android-support-v4  v 26.0.2 (api 26) jar file

### ISSUE THREAD

**Issue by mohamadrezash** [dandar3/android-support-v4#1]
hey dear.
i need to v 26.0.2 android-support-v4 jar file but the latest release that include jar file is 24.1.1 
please help

**Comment by dandar3** [comment]
Hi

I see it now, the date on the `libs` folder is a year old and the comment says 24.2.1, sorry about that, looking into it.

**Comment by dandar3** [comment]
Actually that is not a problem, what happens is `support-v4` was stripped of all classes which moved into dependant projects. It only contains a BuildConfig.class that hasn't changed in the last few versions, that is why it didn't get refreshed by the Git client.

You wil see it when you open the JAR with [JD-GUI](http://jd.benow.ca/). You can do the same on the one from Google Maven repository ([support-v4-26.0.2.aar](https://maven.google.com/com/android/support/support-v4/26.0.2/support-v4-26.0.2.aar))

PS: Aside from this, recommending to watch the [android-support-library-README](https://github.com/dandar3/android-support-library-README) project and to use the video instructions at the end of it on how to easily download an Android Support Library library set.
